// <auto-generated />
using System;
using Gamza.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gamza.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201175452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Gamza.Models.BattleParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<double>("AttackCoolTime")
                        .HasColumnType("double");

                    b.Property<float>("AttackSpeed")
                        .HasColumnType("float");

                    b.Property<Guid>("BattleId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHP")
                        .HasColumnType("int");

                    b.Property<float>("MoveSpeed")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.ToTable("BattleParticipants");
                });

            modelBuilder.Entity("Gamza.Models.BattleSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EndBattle")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartBattle")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("Gamza.Models.CombatLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BattleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Payload")
                        .HasColumnType("longtext");

                    b.Property<long?>("SourceParticipantId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TargetParticipantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CombatLogs");
                });

            modelBuilder.Entity("Gamza.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MinLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "warrior",
                            MinLevel = 10,
                            Name = "워리어",
                            Tier = 1
                        },
                        new
                        {
                            Id = 10,
                            Code = "knight",
                            MinLevel = 30,
                            Name = "나이트",
                            ParentId = 1,
                            Tier = 2
                        },
                        new
                        {
                            Id = 11,
                            Code = "spearman",
                            MinLevel = 30,
                            Name = "스피어맨",
                            ParentId = 1,
                            Tier = 2
                        },
                        new
                        {
                            Id = 12,
                            Code = "ronin",
                            MinLevel = 30,
                            Name = "로닌",
                            ParentId = 1,
                            Tier = 2
                        },
                        new
                        {
                            Id = 20,
                            Code = "paladin",
                            MinLevel = 70,
                            Name = "팔라딘",
                            ParentId = 10,
                            Tier = 3
                        },
                        new
                        {
                            Id = 21,
                            Code = "dragon_knight",
                            MinLevel = 70,
                            Name = "드래곤 나이트",
                            ParentId = 11,
                            Tier = 3
                        },
                        new
                        {
                            Id = 22,
                            Code = "blade",
                            MinLevel = 70,
                            Name = "블레이드",
                            ParentId = 12,
                            Tier = 3
                        },
                        new
                        {
                            Id = 2,
                            Code = "thief",
                            MinLevel = 10,
                            Name = "도적",
                            Tier = 1
                        },
                        new
                        {
                            Id = 30,
                            Code = "assassin",
                            MinLevel = 30,
                            Name = "어쌔신",
                            ParentId = 2,
                            Tier = 2
                        },
                        new
                        {
                            Id = 31,
                            Code = "shadowdancer",
                            MinLevel = 30,
                            Name = "쉐도우댄서",
                            ParentId = 2,
                            Tier = 2
                        },
                        new
                        {
                            Id = 32,
                            Code = "phantom",
                            MinLevel = 30,
                            Name = "팬텀",
                            ParentId = 2,
                            Tier = 2
                        },
                        new
                        {
                            Id = 40,
                            Code = "reaper",
                            MinLevel = 70,
                            Name = "리퍼",
                            ParentId = 30,
                            Tier = 3
                        },
                        new
                        {
                            Id = 41,
                            Code = "specter",
                            MinLevel = 70,
                            Name = "스펙터",
                            ParentId = 31,
                            Tier = 3
                        },
                        new
                        {
                            Id = 42,
                            Code = "raven",
                            MinLevel = 70,
                            Name = "레이븐",
                            ParentId = 32,
                            Tier = 3
                        },
                        new
                        {
                            Id = 3,
                            Code = "mage",
                            MinLevel = 10,
                            Name = "법사",
                            Tier = 1
                        },
                        new
                        {
                            Id = 50,
                            Code = "archMage",
                            MinLevel = 30,
                            Name = "아크메이지",
                            ParentId = 3,
                            Tier = 2
                        },
                        new
                        {
                            Id = 51,
                            Code = "darkMage",
                            MinLevel = 30,
                            Name = "흑마법사",
                            ParentId = 3,
                            Tier = 2
                        },
                        new
                        {
                            Id = 52,
                            Code = "timeMage",
                            MinLevel = 30,
                            Name = "시간법사",
                            ParentId = 3,
                            Tier = 2
                        },
                        new
                        {
                            Id = 60,
                            Code = "grandsorcerer",
                            MinLevel = 70,
                            Name = "그랜드소서러",
                            ParentId = 50,
                            Tier = 3
                        },
                        new
                        {
                            Id = 61,
                            Code = "necromancer",
                            MinLevel = 70,
                            Name = "네크로맨서",
                            ParentId = 51,
                            Tier = 3
                        },
                        new
                        {
                            Id = 62,
                            Code = "chronotrigger",
                            MinLevel = 70,
                            Name = "크로노트리거",
                            ParentId = 52,
                            Tier = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "archer",
                            MinLevel = 10,
                            Name = "궁수",
                            Tier = 1
                        },
                        new
                        {
                            Id = 70,
                            Code = "hunter",
                            MinLevel = 30,
                            Name = "헌터",
                            ParentId = 4,
                            Tier = 2
                        },
                        new
                        {
                            Id = 71,
                            Code = "sniper",
                            MinLevel = 30,
                            Name = "명사수",
                            ParentId = 4,
                            Tier = 2
                        },
                        new
                        {
                            Id = 72,
                            Code = "TrickArcher",
                            MinLevel = 30,
                            Name = "트릭아처",
                            ParentId = 4,
                            Tier = 2
                        },
                        new
                        {
                            Id = 80,
                            Code = "beastmaster",
                            MinLevel = 70,
                            Name = "비스트마스터",
                            ParentId = 70,
                            Tier = 3
                        },
                        new
                        {
                            Id = 81,
                            Code = "deadeye",
                            MinLevel = 70,
                            Name = "데드아이",
                            ParentId = 71,
                            Tier = 3
                        },
                        new
                        {
                            Id = 82,
                            Code = "mirage",
                            MinLevel = 70,
                            Name = "미라지",
                            ParentId = 72,
                            Tier = 3
                        },
                        new
                        {
                            Id = 5,
                            Code = "healer",
                            MinLevel = 10,
                            Name = "힐러",
                            Tier = 1
                        },
                        new
                        {
                            Id = 90,
                            Code = "cleric",
                            MinLevel = 30,
                            Name = "클레릭",
                            ParentId = 5,
                            Tier = 2
                        },
                        new
                        {
                            Id = 91,
                            Code = "onmyoji",
                            MinLevel = 30,
                            Name = "음양사",
                            ParentId = 5,
                            Tier = 2
                        },
                        new
                        {
                            Id = 92,
                            Code = "alchemist",
                            MinLevel = 30,
                            Name = "연금술사",
                            ParentId = 5,
                            Tier = 2
                        },
                        new
                        {
                            Id = 100,
                            Code = "priest",
                            MinLevel = 70,
                            Name = "프리스트",
                            ParentId = 90,
                            Tier = 3
                        },
                        new
                        {
                            Id = 101,
                            Code = "sorcerer",
                            MinLevel = 70,
                            Name = "점술사",
                            ParentId = 91,
                            Tier = 3
                        },
                        new
                        {
                            Id = 102,
                            Code = "homunculus",
                            MinLevel = 70,
                            Name = "호문쿨루스",
                            ParentId = 92,
                            Tier = 3
                        });
                });

            modelBuilder.Entity("Gamza.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RewardExp")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("Gamza.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AttackSpeed")
                        .HasColumnType("float");

                    b.Property<int>("CurrentJobId")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<long>("ExpToNext")
                        .HasColumnType("bigint");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<int?>("Job")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MP")
                        .HasColumnType("int");

                    b.Property<int>("MagicAttack")
                        .HasColumnType("int");

                    b.Property<int>("MaxHP")
                        .HasColumnType("int");

                    b.Property<int>("MaxMP")
                        .HasColumnType("int");

                    b.Property<float>("MoveSpeed")
                        .HasColumnType("float");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PhysicalAttack")
                        .HasColumnType("int");

                    b.Property<int>("PlayerSecondStauts")
                        .HasColumnType("int");

                    b.Property<int>("PlayerStauts")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentJobId");

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Gamza.Models.PlayerJobHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerJobHistories");
                });

            modelBuilder.Entity("Gamza.Models.RewardGrant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BattleId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BattleId", "PlayerId")
                        .IsUnique();

                    b.ToTable("RewardGrants");
                });

            modelBuilder.Entity("Gamza.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoginID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gamza.Models.BattleParticipant", b =>
                {
                    b.HasOne("Gamza.Models.BattleSession", "Battle")
                        .WithMany("Participants")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battle");
                });

            modelBuilder.Entity("Gamza.Models.Job", b =>
                {
                    b.HasOne("Gamza.Models.Job", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Gamza.Models.Player", b =>
                {
                    b.HasOne("Gamza.Models.Job", "CurrentJob")
                        .WithMany()
                        .HasForeignKey("CurrentJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gamza.Models.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentJob");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gamza.Models.PlayerJobHistory", b =>
                {
                    b.HasOne("Gamza.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gamza.Models.Player", "Player")
                        .WithMany("JobHistories")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Gamza.Models.BattleSession", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Gamza.Models.Job", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Gamza.Models.Player", b =>
                {
                    b.Navigation("JobHistories");
                });

            modelBuilder.Entity("Gamza.Models.User", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
